import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, "..");
const entryPath = path.join(projectRoot, "src", "browser-entry.js");
const outputPath = path.join(projectRoot, "web", "game.bundle.js");
const modules = [];
const moduleIds = new Map();

function resolveDependency(parentPath, request) {
  if (!request.startsWith(".")) {
    throw new Error(`Browser bundle only supports local modules. Found '${request}' in ${parentPath}`);
  }
  const candidate = path.resolve(path.dirname(parentPath), request);
  const paths = path.extname(candidate) ? [candidate] : [`${candidate}.js`, path.join(candidate, "index.js")];
  const resolved = paths.find((item) => fs.existsSync(item));
  if (!resolved) throw new Error(`Cannot resolve '${request}' from ${parentPath}`);
  return resolved;
}

function collect(filePath) {
  const normalized = path.normalize(filePath);
  if (moduleIds.has(normalized)) return moduleIds.get(normalized);
  const id = modules.length;
  moduleIds.set(normalized, id);
  modules.push(null);
  let source = fs.readFileSync(normalized, "utf8");
  source = source.replace(/require\((['"])(.+?)\1\)/g, (_match, _quote, request) => {
    const dependencyPath = resolveDependency(normalized, request);
    const dependencyId = collect(dependencyPath);
    return `__require(${dependencyId})`;
  });
  modules[id] = {
    id,
    name: path.relative(projectRoot, normalized).replaceAll("\\", "/"),
    source
  };
  return id;
}

const entryId = collect(entryPath);
const moduleTable = modules.map((module) => {
  return `${module.id}: function(module, exports, __require) {\n// ${module.name}\n${module.source}\n}`;
}).join(",\n");

const banner = `/* Wasteland Echo Windows desktop bundle. Generated by scripts/build-web.mjs. */`;
const bundle = `${banner}
(function () {
  "use strict";
  const __modules = {
${moduleTable}
  };
  const __cache = {};
  function __require(id) {
    if (__cache[id]) return __cache[id].exports;
    const module = { exports: {} };
    __cache[id] = module;
    __modules[id](module, module.exports, __require);
    return module.exports;
  }
  __require(${entryId});
})();
`;

fs.writeFileSync(outputPath, bundle, "utf8");
console.log(`Built ${path.relative(projectRoot, outputPath)} (${Buffer.byteLength(bundle)} bytes, ${modules.length} modules)`);
